version:          "007a--31-May-2022"
copyright:        "2022-2022"
description:
  Ever did something and forgot how years later?
  Or months later? Or even weeks later?
  Therefore, keep a memo about it!
tagline:          "Keep a memo before you forget about it!"
disclaimer:
  I have spoken.
keywords:         "jekyll, testing"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "TOC"
  link:           "/002.html"
- navbar:         "Listing"
  link:           "/000.html"
- navbar:         "About"
  link:           "/ABOUT/"
- navbar:         "GitHub"
  link:           "https://github.com/yforku/memos/"
- navbar:         "GitHub Page"
  link:           "https://memos.vlsm.org/"
title:            "MEMOS.vlsm.org"
lang:             "en-US"
author:           "C. BinKadal"
address:          "Sendirian, Berhad"
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://memos.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/yforku/memos/"
google_analytics: "G-KYFCYENZ4E"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

