version:          "0005--30-May-2022"
copyright:        "2021-2022"
description:
  This is MEMOS.vlsm.org using a
  GitHub Page Template description.
  See also tagline.
tagline:          "This is MEMO.vlsm.org tagline"
disclaimer:
  I have spoken.
keywords:         "jekyll, testing"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "Links"
  link:           "/LINKS/"
- navbar:         "Tips"
  link:           "/TIPS/"
- navbar:         "Zip File"
  link:           "/template.zip"
- navbar:         "TarBall"
  link:           "/template.tar.bz2"
- navbar:         "GitHub"
  link:           "https://github.com/yforku/memos/"
- navbar:         "Listing"
  link:           "/000.html"
- navbar:         "About"
  link:           "/ABOUT/"
- navbar:         "GitHub Page"
  link:           "https://memos.vlsm.org/"
title:            "MEMOS.vlsm.org"
lang:             "en-US"
author:           "J. Walker"
address:          "Box 7, Mawitaan, Bangalla."
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://memos.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/yforku/memos/"
google_analytics: "G-KYFCYENZ4E"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

